version: '3'
services:
  mongo:
    tty: true
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    container_name: "mongo"
    ports:
      - "27017:27017"
  flask:
    tty: true
    build: .
    container_name: "flask"
    ports:
      - "5000:5000"
    environment:
      - name=docker
  redis:
    tty: true
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

